config/routes.rb
Tianye::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'home#index', :as => 'home'
  get 'home/index' => 'home#index'
  
  resources :categories
  resources :products
  resources :services
  resources :solutions
  resources :supports
  resources :companies
  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :series
  validates :title, presence: true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :series
  has_one :configuration
  
  has_attached_file :image, :styles => {:medium => '300x300', :thumb => '100x100'}
                    
end

app/models/series.rb
class Series < ActiveRecord::Base
  belongs_to :category
  has_many :products
  
  validates :title, presence: true
  validates :category_id, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :image, :styles => {:medium => '217x165', :thumb => '178x133'}
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  has_attached_file :image, :styles => {:medium => '217x165', :thumb => '178x133'}
end

app/models/support.rb
class Support < ActiveRecord::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout 'products'
  def index
    
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  layout 'products'
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  layout 'products'
  
  def index
    @supports = Support.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/companies/show.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right" style="width:730px;">
  <div class="articles" style="width:708px;float:left;height:auto;overflow:hidden;margin:0px;padding:3px 10px 0px 10px;border-left:#E4E4E4 solid 1px;">
  <div class="node">
  <div class="name">Home » About US >> <%= @company.title %></div>
  </div>
  <div class="content" style="width:718px;float:left;margin:0px;height:auto;overflow:hidden;padding:0px;">  
    <div class="guo_content">
      <div class="guo_block" align="left">	
		<h3><%= @company.title%></h3>
		<%= @company.content.html_safe %>
      </div>
   </div>               
   <div align="center"><br>&nbsp;<br><br></div>
 </div>
  </div>
  </div> 
	<div class="left" align="left">
		<div class="prolist" style=" border:1px solid #e9e9e9;">
		  <div class="nav" style="margin:10px">
			  <div class="name" style="color:#FF9900; font-size:16px">About Us</div>
			  <ul>
				<% Company.all.each do |c| %>
				  <li><%= link_to c.title, company_path(c) %></li>
				<%end %>
			  </ul>
			</div>
		</div>
		  <div class="prolist" style=" border:1px solid #e9e9e9;margin-top:20px">
		    <div class="nav" style="margin:10px">
			    <div class="name" style="color:#FF9900; font-size:16px">Contact Us</div>
				<ul>
					<li>Shanghai TianyeIT CO, LTD</li>
					<li>Tel: +86-21-60445500 </li>
					<li>E-Mail:   sales@tianyeit.com </li>
					<li>Online Skype: nandcon /   dtt015 </li>
					<li>Addr: No.200, East of Guoding   Road, Shanghai </li>
				</ul>
		    </div>
		  </div>
	</div>

  </div>
</div>
</div>

app/views/products/index.html.erb
<div align="center">
  <div class="main">
    <div class="all">
      <div class="right" style="width:730px;">
        <div class="articles" style="width:708px;float:left;height:auto;overflow:hidden;margin:0px;padding:3px 10px 0px 10px;border-left:#E4E4E4 solid 1px;">
          <div class="node">
            <div class="name">Home » Products</div>
          </div>
          <div class="content" style="width:718px;float:left;margin:0px;height:auto;overflow:hidden;padding:0px;">
            <div class="guo_content">
          	  <% @products.each do |p| %>
			    <div class="guo_block" align="left">	
		        <table width="680" border="0" cellspacing="0" cellpadding="0">
	              <tbody>
		            <tr>
	          		  <td width="210">
					    <%= link_to image_tag(p.image.url, :class => 'guo_img'), product_path(p) %>
	          		  </td>
	          		  <td valign="top">
		        		<ul class="guo_blist">
	              		    <h3><%= p.title %></h3>
	              			<p><%= p.description %><p> 
				  			<h3><span><%= link_to 'MORE >>', product_path(p) %></span></h3>   																		
		        		</ul>
		      		  </td>
	       			</tr>
	     		  </tbody>
	    		</table>
	  		  </div>
 			  <% end %>
			</div>               
   		  </div>
  		</div>
  	  </div> 
  	<div class="left" align="left">
		<%= render '/shared/contact' %>
	</div>

  </div>
</div>
</div>

app/views/products/show.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right">
      <div class="articles" style="font-weight:200;">
        <div class="node">
          <div class="name">Home » <%= @product.title %> </div>
      </div>
      <div class="content">
        <div class="title"><%= @product.title %><br><br></div>

        <div align="center">&nbsp;<br>
		  <%= image_tag @product.image.url %>
	   </div>
      <div class="anything">
		<!-- configuration -->
		<table width="95%" border='1' cellspacing="0", cellpadding="0">
		  <tbody>
			<% @product.configuration.attributes.each do |key, value| %>
			  <% unless value.blank? || ['id','product_id','created_at', 'updated_at'].include?(key) %>
		  	  <tr>
			    <td style="padding-left:5px"><b><%= key.gsub(/_/,' ').upcase %></b></td>
			    <td align="center"><%= value %></td>
			  <tr>
			  <% end %>
			<% end %>
		  </tbody>
		</table>
      </div>
      
      </div>
      </div>
       <div>&nbsp;</div>
  </div> 
<div class="left" align="left">
	<%= render '/shared/contact' %>
</div>

  </div>
</div>
</div>

app/views/services/index.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right" style="width:730px;">
  <div class="articles" style="width:708px;float:left;height:auto;overflow:hidden;margin:0px;padding:3px 10px 0px 10px;border-left:#E4E4E4 solid 1px;">
  <div class="node">
  <div class="name">Home » Services</div>
  </div>
  <div class="content" style="width:718px;float:left;margin:0px;height:auto;overflow:hidden;padding:0px;">
    <div style="margin:10px; line-height:22px; text-align:left">TianyeIT provides design, development and manufacturing services for a variety of embedded platforms, supported by numerous operating systems. TianyeIT customers stay ahead of the pack and profit from a faster time-to-market, whilst leveraging TianyeIT’s rich experience in embedded solution development.</div>
   
<div class="guo_content">
<% @services.each do |s| %>
<div class="guo_block" align="left">	
	<table width="680" border="0" cellspacing="0" cellpadding="0">
  <tbody><tr>
<td width="210">	
	<%= link_to image_tag(s.image.url(:thumb), :class => 'guo_img'), service_path(s)%>
</td>
<td valign="top"><ul class="guo_blist">
<h3><%= s.title %></h3>
<%= s.description %>
<h3><span><%= link_to 'More >>' , service_path(s) %></span></h3>   																		
	</ul></td>
  </tr>
</tbody></table>
	</div>
<% end %>
		             	
   </div>               
  <div align="center"><br>&nbsp;<br><br></div>
  </div>
  </div>
  </div> 
	<div class="left" align="left">
		<%= render '/shared/contact' %>
	</div>

  </div>
</div>
</div>

app/views/services/show.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right">
      <div class="articles" style="font-weight:200;">
        <div class="node">
          <div class="name">Home » Service >> <%= @service.title %> </div>
      </div>
      <div class="content">
        <div class="title"><%= @service.title %><br><br></div>

        <div align="center">&nbsp;<br>
		  <%= image_tag @service.image.url %>
	   </div>
      <div class="anything">
	    <p><%= @service.description %></p>
		<p><%= @service.detail.html_safe %></p>			
      </div>
      
      </div>
      </div>
       <div>&nbsp;</div>
  </div> 

  	<div class="left" align="left">
		<%= render '/shared/contact' %>
	</div>

  </div>
</div>
</div>

app/views/supports/index.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right">
  <div class="articles">
  <div class="node">
  <div class="name">Home » Contact Support  </div>
  </div>
  <div class="content">
  <div class="title"><%= @supports.first.title %></div>
  <div class="anything" style="line-height:30px"><div class="dym" style="text-indent:2em;">
	<%= @supports.first.content.html_safe %>

	
</div>
</div>

  </div>
  </div>
  </div> 
<div class="left" align="left">
  <%= render '/shared/contact'%>

  </div>
</div>
</div>