config/routes.rb
Tianye::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'home#index', :as => 'home'
  get 'home/index' => 'home#index'
  
  resources :categories
  resources :products
  resources :services
  resources :solutions
  resources :supports
  resources :companies
  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :series
  validates :title, presence: true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :series
  has_one :configuration
  
  has_attached_file :image, :styles => {:medium => '300x300', :thumb => '100x100'}
                    
end

app/models/series.rb
class Series < ActiveRecord::Base
  belongs_to :category
  has_many :products
  
  validates :title, presence: true
  validates :category_id, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :image, :styles => {:medium => '217x165', :thumb => '178x133'}
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  has_attached_file :image, :styles => {:medium => '217x165', :thumb => '178x133'}
end

app/models/support.rb
class Support < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  layout 'products'
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  layout 'products'
  def index
    @solutions = Solution.all
  end

  def show
    @solution = Solution.find(params[:id])
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  layout 'products'
  
  def index
    @supports = Support.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/solutions/index.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right" style="width:730px;">
  <div class="articles" style="width:708px;float:left;height:auto;overflow:hidden;margin:0px;padding:3px 10px 0px 10px;border-left:#E4E4E4 solid 1px;">
  <div class="node">
  <div class="name">Home » Solutions</div>
  </div>
  <div class="content" style="width:718px;float:left;margin:0px;height:auto;overflow:hidden;padding:0px;">
    <div style="margin:10px; line-height:22px; text-align:left">TianyeIT customized solutions are engineered and manufactured for all industrial sectors. Fully integrated systems provide the critical components to optimize your product design, development and manufacture. TianyeIT experts have developed end-to-end solutions that deliver core technology capabilities across a unique range of industries.
	</div>
   
<div class="guo_content">
<% @solutions.each do |s| %>
<div class="guo_block" align="left">	
	<table width="680" border="0" cellspacing="0" cellpadding="0">
  <tbody><tr>
<td width="210">	
	<%= link_to image_tag(s.image.url(:thumb), :class => 'guo_img'), service_path(s)%>
</td>
<td valign="top"><ul class="guo_blist">
<h3><%= s.title %></h3>
<%= s.description %>
<h3><span><%= link_to 'More >>' , solution_path(s) %></span></h3>   																		
	</ul></td>
  </tr>
</tbody></table>
	</div>
<% end %>
		             	
   </div>               
  <div align="center"><br>&nbsp;<br><br></div>
  </div>
  </div>
  </div> 
	<div class="left" align="left">
		<%= render '/shared/contact' %>
	</div>

  </div>
</div>
</div>

app/views/solutions/show.html.erb
<div align="center">
  <div class="main">
  <div class="all">
 <div class="right">
      <div class="articles" style="font-weight:200;">
        <div class="node">
          <div class="name">Home » Solutions >> <%= @solution.title %> </div>
      </div>
      <div class="content">
        <div class="title"><%= @solution.title %><br><br></div>

        <div align="center">&nbsp;<br>
		  <%= image_tag @solution.image.url %>
	   </div>
      <div class="anything">
	    <p><%= @solution.description %></p>
		<p><%= @solution.detail.html_safe %></p>			
      </div>
      
      </div>
      </div>
       <div>&nbsp;</div>
  </div> 

  	<div class="left" align="left">
		<%= render '/shared/contact' %>
	</div>

  </div>
</div>
</div>