config/routes.rb
Tianye::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'home#index', :as => 'home'
  get 'home/index' => 'home#index'
  
  resources :categories
  resources :products
  resources :services
  resources :solutions
  resources :supports
  resources :companies
  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :series
  validates :title, presence: true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :series
  has_one :configuration
  
  has_attached_file :image, :styles => {:medium => '300x300', :thumb => '100x100'}
                    
end

app/models/series.rb
class Series < ActiveRecord::Base
  belongs_to :category
  has_many :products
  
  validates :title, presence: true
  validates :category_id, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_attached_file :image, :styles => {:medium => '217x165', :thumb => '178x133'}
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  has_attached_file :image, :styles => {:medium => '217x165', :thumb => '178x133'}
end

app/models/support.rb
class Support < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tianye</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigater' %>
<%= yield %>

</body>
</html>

app/views/layouts/categories.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tianye</title>
  <%= stylesheet_link_tag    "home", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'shared/navigater' %>
	<%= yield %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tianye</title>
  <link href="/stylesheets/all.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/mt_style.css" rel="stylesheet" type="text/css">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="/javascripts/lwn.js"></script>
 
  <%= csrf_meta_tags %>

</head>
<body onload="init();" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<div align="center">
  <div style="width:1002px; height:82px; position:relative; overflow:hidden; background:#FFFFFF">
    <div align="left" style="width:960px;"><img src="/images/logo.jpg"></div>
  </div>
</div>

 <div align="center">
  <div style="width:1002px; height:39px;background:#FFFFFF">
  
  <div align="left" style="width:960px; background-color:#202020; height:39px;position:relative; "> 
    <div class="link" style="width:928px; height:39px; position:absolute; left: 0px; top: 0px;">
	<table border="0" cellpadding="0" cellspacing="0" width="735" align="left">
                <tbody> 
                  <tr> 
    <td><a style="background-color:#666666; padding-left:20px; padding-right:10px; width:60px; margin-right:-30px" href="/" id="menu1">HOME</a></td>
    <td><%= link_to 'Products', products_path %></td>
    <td><a href="/services.php?sort=2" id="menu3">SERVICES</a></td>
    <td><a href="/solutions.php?sort=90" id="menu4">SOLUTIONS</a></td>
    <td><a href="/about.php?id=3" id="menu5">SUPPORT</a></td>
    <td><a href="/about.php?id=11" id="menu6">COMPANY</a></td>
    <td><a href="/about.php?id=12" id="menu7">CONTACT US</a></td>
    </tr>
                </tbody> 
        </table>

      </div>
	 <div style="width:195px; height:30px; position:absolute; left: 761px; top: 5px; background:url(/images/search.jpg) no-repeat">
	 	 <form id="productSearch" name="productSearch" action="/product.php" method="post">
<input type="text" id="keywords" name="keyword" value="Enter the product name" onfocus="if(value==defaultValue){value='';this.style.color='#000'}" onblur="if(!value){value=defaultValue;this.style.color='#999'}" maxlength="50">
<input type="submit" id="searchbtn" align="middle" class="i_p_btn" value="">
</form>
	 </div>
  </div>
  </div>
</div>
	
	
<div align="center">
  <div style="width:1002px; height:365px; position:relative; overflow:hidden; background:#FFFFFF; padding:15px 0 15px 0;">
  <div style="width:960px; height:365px; overflow:hidden">
  <div id="focus">
		<ul style="left: -2880px; width: 3840px;">
		    <li><a href="#" target="_blank"><img src="/img/simple_img_1.jpg" alt=""></a></li>
			<li><a href="#" target="_blank"><img src="/img/simple_img_2.jpg" alt=""></a></li>
			<li><a href="#" target="_blank"><img src="/img/simple_img_3.jpg" alt=""></a></li>
			<li><a href="#" target="_blank"><img src="/img/simple_img_4.jpg" alt=""></a></li>		
		</ul>
	   

	   <div class="preNext pre" style="opacity: 0.2;"></div>
	   <div class="preNext next" style="opacity: 0.2;"></div>
	</div></div>
  </div>
</div>
<div align="center">
  <div style="width:1002px; height:310px; position:relative; overflow:hidden; background:#FFFFFF; text-align:left; line-height:21px; font-family:Arial, Helvetica, sans-serif">
    <div style="width:439px; height:218px; position:absolute; left: 29px; top: 24px;">
      <div style="font-size:16px; color:#196193; font-weight:bold">Welcome to TianyeIT</div>
	  <div style="color:#2c2f36; font-weight:bold">Leading System On Module manufacturer</div>
	  
      <div>
        <div id="Mod157">
          <div>
            <div>TianyeIT is a leading manufacturer of computer-on-module boards and miniature PC systems. TianyeIT's  products excel with an advanced set of features, outstanding level of integration, high reliability and affordable prices. Annual manufacturing rate of over 10,000 boards and systems positioning TianyeIT as a key player in embedded market. 
			</div>
          </div>
        </div>
      </div>
	  
      <div><img src="/images/about1.jpg"></div>
    </div>
	<div style="width:10px; height:228px; position:absolute; left: 488px; top: 26px; border-right:1px dotted #CCCCCC"></div>
	<div style="width:312px; height:228px; position:absolute; left: 525px; top: 7px;">
	 <div style="font-size:16px; color:#196193; font-weight:bold">LATEST NEWS &amp; PRODUCTS</div>
	  <div style="color:#2c2f36; font-weight:bold"><a title="工信部：上半年软件效益不断向好" href="/infov.php?id=118">工信部：上半年软件效益不断向好</a></div>
 <div>2013-08-06</div>
	<div> <a href="/infov.php?id=118" class="b1"></a></div>
	
	<div><a href="/infov.php?id=118"><img src="images/more.jpg" border="0"></a></div>
</div>
	<div style="width:102px; height:51px; position:absolute; left: 857px; top: 23px;"><img src="images/m2.jpg" width="128" height="103"></div>
	<div style="width:102px; height:51px; position:absolute; left: 874px; top: 158px;"><img src="images/m3.jpg" width="100" height="113"></div>
	</div>
</div>
<div align="center">
    <div style="width:1002px; height:221px; position:relative; overflow:hidden; background:url(images/m5.jpg) center top no-repeat; background-color:#FFFFFF; text-align:left; line-height:21px; font-family:Arial, Helvetica, sans-serif">
      <div style="width:191px; height:159px; position:absolute; left: 35px; top: 22px;">
	   <div style="font-size:16px; color:#ffffff; font-weight:bold">PRODUCTS</div>
	  <div style="color:#82b5d0; font-weight:bold">Your product vision becomes an affordable and immediate reality.</div>
	  	  <div class="news">
		  <ul class="w2">
		  <li><a href="/product.php">» Computer In Package</a> </li>
		   <li><a href="/product.php?sort=3">» Evaluation Kits</a> </li>
		   <li><a href="/product.php?sort=13">» Extension Boards</a> </li>
		   </ul>
		  </div>
      </div>
	  <div style="width:191px; height:51px; position:absolute; left: 278px; top: 23px;">
	  	   <div style="font-size:16px; color:#ffffff; font-weight:bold">SERVICES</div>
	  <div style="color:#82b5d0; font-weight:bold">Stay ahead of the pack and profit from faster time to market.</div>
	  	  <div class="news">
		  <ul class="w2">
		  <li><a href="/services.php?sort=2">» Board Design Services</a> </li>
		   <li><a href="/services.php?sort=2">» Software Development Services</a> </li>
		   <li><a href="/services.php?sort=2">» Manufacturing Services</a> </li>
		   </ul>
		  </div>
	  </div>
	  <div style="width:213px; height:82px; position:absolute; left: 523px; top: 21px;">
	  	   <div style="font-size:16px; color:#ffffff; font-weight:bold">SOLUTIONS</div>
	  <div style="color:#82b5d0; font-weight:bold">Custom engineered solutions for all industrial sectors.</div>
	  	  <div class="news">
		  <ul class="w2">
		  <li><a href="/solutions.php?sort=90">» Medical</a> </li>
		   <li><a href="/solutions.php?sort=90">» Agriculture</a> </li>
		   <li><a href="/solutions.php?sort=90">» Automotive</a> </li>
		   <li><a href="/solutions.php?sort=90">» Control Systems</a> </li>
		    <li><a href="/solutions.php?sort=90">» Multimedia</a> </li>
		   </ul>
		  </div>
	  </div>
	  <div style="width:200px; height:173px; position:absolute; left: 768px; top: 22px;">
	  	  	   <div style="font-size:16px; color:#ffffff; font-weight:bold">SUPPORT</div>
	  <div style="color:#82b5d0; font-weight:bold">Technical support for Hardware and Software developers.</div>
	  	  <div class="news">
		  <ul class="w2">
		  <li><a href="/about.php?id=18">» TianyeIT Wiki</a> </li>
		   <li><a href="/about.php?id=12">» Contact Support</a> </li>
		   </ul>
		  </div>
	  </div>
    </div>
</div>
<div align="center">
  <div style="width:1002px; height:106px; position:relative; overflow:hidden; background:#FFFFFF">
    <div style="margin:0px 20px 0 20px; background:#d2d2d2; text-align:left; line-height:23px">
      <div style="color:#FFFFFF; font-size:16px; padding:10px 0 10px 20px">DOWNLOAD CATALOG</div>
	  <div style="padding-left:20px; padding-bottom:10px"><img src="images/pdf.jpg"> </div>
	  </div>
  </div>
</div>
<div align="center">
  <div style="width:1002px; height:111px; position:relative; overflow:hidden; background:#FFFFFF; line-height:21px; text-align:left">
  <div style="width:102px; height:51px; position:absolute; left: 21px; top: 0px;"><img src="images/pinpai.jpg" width="484" height="109"></div>
  <div style="width:315px; height:51px; position:absolute; left: 524px; top: 9px;">All TianyeIT production is performed at fully ISO 13485 compliant facilities, satisfying international customer and regulatory requirements for a broad range of industries including medical devices and related services.</div>
 <div style="width:102px; height:51px; position:absolute; left: 867px; top: 11px;"><img src="images/iso.jpg" width="91" height="86"></div> 
</div>
</div>
<div align="center">
  
<div style="width:1002px; height:161px; position:relative; overflow:hidden; background:#111111; line-height:21px; text-align:left">
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 31px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">PRODUCTS</div>
	  <div><a href="/">System On Module (SOM)</a></div>
	  <div><a href="/">Evaluation Kits</a></div>
	  <div><a href="/">Single Board Computers</a></div>
	  <div><a href="/">Extension Boards</a></div>
  </div>
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 231px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Latest SoMs</div>
	  <div>
	    <div><a href="#">SOM2416 - SAMSUNG 2416</a><a href="/"></a></div>
        <div><a href="#">SOM6410 - SAMSUNG 6410</a><a href="/"></a></div>
        <div><a href="#">CIP30X - TI AM335X</a></div>
        <div>
          <p><a href="#">CIP31X - TI AM37XX</a></p>
        </div>
        <div>
          <p><a href="#">CIP41X - TI OMAP44XX</a></p>
        </div>
      <a href="/"></a></div>
</div>
  
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 431px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Support</div>
	  <div><a href="#">Contact Support</a><a href="/"></a></div>
	  <div><a href="#" rel="nofollow" target="_blank">TianyeIT Wiki</a><a href="/"></a></div>
  </div>
  
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 631px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Company</div>
	  <div>
	    <div><a href="/about.php?id=11">About TianyeIT</a></div>
        <div><a href="news.php">News Room</a></div>
        <div><a href="/about.php?id=12">Contact Us</a></div>
	  </div>
  </div>
  
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 831px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Connect with us</div>
	  <div><a href="/">Face book</a></div>
	  <div><a href="/">Twitter</a></div>
  </div>
  
  </div>
<div style="width:1002px; height:51px; position:relative; overflow:hidden; background:#1a1a1a; line-height:21px; text-align:left">
  <div style="width:530px; height:31px; position:absolute; left: 32px; top: 13px; color:#4b4b38">Copyright © 2013 TianyeIT - Leading System on Module manufacturer. All Rights Reserved.</div>
  <div style="width:102px; height:25px; position:absolute; left: 809px; top: 11px;"></div>
</div>

</div>
 
</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tianye</title>
  <link href="/stylesheets/all.css" rel="stylesheet" type="text/css">
  <link href="/stylesheets/main.css" rel="stylesheet" type="text/css">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="/javascripts/lwn.js"></script>
 
  <%= csrf_meta_tags %>

</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<div align="center">
  <div style="width:1002px; height:82px; position:relative; overflow:hidden; background:#FFFFFF">
    <div align="left" style="width:960px;"><img src="/images/logo.jpg"></div>
  </div>
</div>

<%= render '/shared/navigater' %>
<div align="center">
  <div style="width:1002px; height:185px; position:relative; overflow:hidden; background:#FFFFFF; padding:15px 0 5px 0;">
    <div style="width:960px; height:185px; overflow:hidden">
      <img src="/images/services.jpg" width="960">
    </div>
  </div>
</div>

<%= yield %>


<div align="center">
  <div style="width:1002px; height:111px; position:relative; overflow:hidden; background:#FFFFFF; line-height:21px; text-align:left">
  <div style="width:102px; height:51px; position:absolute; left: 21px; top: 0px;"><img src="/images/pinpai.jpg" width="484" height="109"></div>
  <div style="width:315px; height:51px; position:absolute; left: 524px; top: 9px;">All TianyeIT production is performed at fully ISO 13485 compliant facilities, satisfying international customer and regulatory requirements for a broad range of industries including medical devices and related services.</div>
 <div style="width:102px; height:51px; position:absolute; left: 867px; top: 11px;"><img src="/images/iso.jpg" width="91" height="86"></div> 
</div>
</div>
<div align="center">
  
<div style="width:1002px; height:161px; position:relative; overflow:hidden; background:#111111; line-height:21px; text-align:left">
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 31px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">PRODUCTS</div>
	  <div><a href="/">System On Module (SOM)</a></div>
	  <div><a href="/">Evaluation Kits</a></div>
	  <div><a href="/">Single Board Computers</a></div>
	  <div><a href="/">Extension Boards</a></div>
  </div>
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 231px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Latest SoMs</div>
	  <div>
	    <div><a href="#">SOM2416 - SAMSUNG 2416</a><a href="/"></a></div>
        <div><a href="#">SOM6410 - SAMSUNG 6410</a><a href="/"></a></div>
        <div><a href="#">CIP30X - TI AM335X</a></div>
        <div>
          <p><a href="#">CIP31X - TI AM37XX</a></p>
        </div>
        <div>
          <p><a href="#">CIP41X - TI OMAP44XX</a></p>
        </div>
      <a href="/"></a></div>
</div>
  
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 431px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Supports</div>
	  	<% Support.all.each do |s| %>
		  <div><%= link_to s.title, supports_path %></div>
		<% end %>
  </div>
  
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 631px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Company</div>
	  <div>
		<% Company.all.each do |c| %>
		  <div><%= link_to c.title, company_path(c) %></div>
		<% end %>
	  </div>
  </div>
  
  <div class="b1" style="width:162px; height:144px; position:absolute; left: 831px; top: 11px;">
    <div style="font-size:14px; color:#ffffff; font-weight:bold">Connect with us</div>
	  <div><a href="/">Face book</a></div>
	  <div><a href="/">Twitter</a></div>
  </div>
  
  </div>
<div style="width:1002px; height:51px; position:relative; overflow:hidden; background:#1a1a1a; line-height:21px; text-align:left">
  <div style="width:530px; height:31px; position:absolute; left: 32px; top: 13px; color:#4b4b38">Copyright © 2013 TianyeIT - Leading System on Module manufacturer. All Rights Reserved.</div>
  <div style="width:102px; height:25px; position:absolute; left: 809px; top: 11px;"></div>
</div>

</div>
 
</body>
</html>

app/views/shared/_contact.html.erb
<div class="prolist" style=" border:1px solid #e9e9e9;">
  <div class="nav" style="margin:10px">
	  <div class="name" style="color:#FF9900; font-size:16px">Categories</div>
	  <ul>
	  <% Category.all.each do |c| %>
	    <li><%= link_to c.title, category_path(c) %></li>
	  <% end %>
	  </ul>
	</div>
</div>
  <div class="prolist" style=" border:1px solid #e9e9e9;margin-top:20px">
    <div class="nav" style="margin:10px">
	    <div class="name" style="color:#FF9900; font-size:16px">Contact Us</div>
		<ul>
			<li>Shanghai TianyeIT CO, LTD</li>
			<li>Tel: +86-21-60445500 </li>
			<li>E-Mail:   sales@tianyeit.com </li>
			<li>Online Skype: nandcon /   dtt015 </li>
			<li>Addr: No.200, East of Guoding   Road, Shanghai </li>
		</ul>
    </div>
  </div>

app/views/shared/_navigater.html.erb
 <div align="center">
  <div style="width:1002px; height:39px;background:#FFFFFF">
  
  <div align="left" style="width:960px; background-color:#202020; height:39px;position:relative; "> 
    <div class="link" style="width:928px; height:39px; position:absolute; left: 0px; top: 0px;">
	<table border="0" cellpadding="0" cellspacing="0" width="735" align="left">
      <tbody> 
        <tr> 
          <td><a style="background-color:#666666; padding-left:20px; padding-right:10px; width:60px; margin-right:-30px" href="/" id="menu1">HOME</a></td>
          <td><%= link_to 'Products', products_path %></td>
          <td><%= link_to 'Services', services_path %></td>
          <td><%= link_to 'Solutions', solutions_path %></td>
          <td><%= link_to 'Support', supports_path %></td>
          <td><%= link_to 'About Us', company_path(1) %></td>
        </tr>
      </tbody> 
     </table>
    </div>
	 <div style="width:195px; height:30px; position:absolute; left: 761px; top: 5px; background:url(/images/search.jpg) no-repeat">
	 	 <form id="productSearch" name="productSearch" action="/product.php" method="post">
			<input type="text" id="keywords" name="keyword" value="Enter the product name" onfocus="if(value==defaultValue){value='';this.style.color='#000'}" 				    onblur="if(!value){value=defaultValue;this.style.color='#999'}" maxlength="50">
            <input type="submit" id="searchbtn" align="middle" class="i_p_btn" value="">
        </form>
	 </div>
  </div>
  </div>
</div>